#! /usr/bin/env node

const { program } = require('commander')
const list = require('./commands/list')

program
    .command('list')
    .description('List of all the TODO task')
    .action(list)

program.parse()